"""
downloader.py
Downloads videos from a list of URLs using yt-dlp.
Marks each video as downloaded (or error) in the SQLite database.
"""

import json
import os
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING

import yt_dlp

if TYPE_CHECKING:
    from db import VideoRecord


def _netscape_cookies(cookies_path: str) -> str | None:
    """
    Convert a Cookie-Editor JSON file to a Netscape-format temp file that
    yt-dlp can consume. Returns the path to the temp file, or None on failure.
    The caller is responsible for deleting the temp file when done.
    """
    try:
        raw = json.loads(Path(cookies_path).read_text(encoding="utf-8"))
    except Exception:
        return None

    lines = ["# Netscape HTTP Cookie File", "# Generated by ClonerCC", ""]
    for c in raw:
        domain      = c.get("domain", "")
        flag        = "TRUE" if domain.startswith(".") else "FALSE"
        path        = c.get("path", "/")
        secure      = "TRUE" if c.get("secure", False) else "FALSE"
        expiry      = int(c.get("expirationDate") or c.get("expiry") or 0)
        name        = c.get("name", "")
        value       = c.get("value", "")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False, encoding="utf-8"
    )
    tmp.write("\n".join(lines))
    tmp.close()
    return tmp.name


def build_ydl_options(output_dir: str, cookies_path: str | None = None) -> dict:
    """Build yt-dlp options for downloading."""
    output_template = str(Path(output_dir) / "%(uploader)s_%(id)s.%(ext)s")

    opts = {
        "outtmpl"             : output_template,
        # TikTok streams are single-file (video+audio muxed) — "best" picks the
        # highest resolution available without re-encoding or merging.
        # Excludes the watermarked "download" format explicitly.
        "format"              : "best[format_id!=download]",
        "merge_output_format" : "mp4",
        "retries"             : 3,
        "fragment_retries"    : 3,
        "progress"            : True,
        "nooverwrites"        : True,
        "ignoreerrors"        : True,
    }

    if cookies_path and Path(cookies_path).exists():
        netscape = _netscape_cookies(cookies_path)
        if netscape:
            opts["cookiefile"] = netscape

    return opts


def download_records(
    records: "list[VideoRecord]",
    output_dir: str,
    cookies_path: str | None = None,
) -> None:
    """
    Download a list of VideoRecord objects and update their status in the DB.
    The video description is extracted from yt-dlp metadata and saved to the DB.

    Args:
        records     : VideoRecord list (from scraper or db.get_pending()).
        output_dir  : Folder where videos will be saved.
        cookies_path: Path to cookies.json for authenticated requests.
    """
    from db import get_db

    if not records:
        print("No records to download.")
        return

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    db = get_db()

    print(f"Output directory  : {os.path.abspath(output_dir)}")
    print(f"Videos to download: {len(records)}\n")

    ydl_opts = build_ydl_options(output_dir, cookies_path=cookies_path)

    # Build a lookup: video_id → record, to use inside the hook
    id_to_record = {r.video_id: r for r in records}

    # Collect metadata (file path + description) keyed by video_id
    meta: dict[str, dict] = {}

    def _on_progress(d: dict) -> None:
        if d.get("status") == "finished":
            info      = d.get("info_dict", {})
            video_id  = str(info.get("id", ""))
            file_path = d.get("filename") or info.get("filepath", "")
            desc      = (info.get("description") or info.get("title") or "").strip()

            if _is_generic_title(desc):
                desc = ""

            if video_id:
                meta[video_id] = {"file": file_path, "description": desc}

                # Write sidecar immediately after each video finishes —
                # the kwai-uploader may already be watching the folder
                record = id_to_record.get(video_id)
                final_desc = desc or (record.description if record else "")
                if file_path and final_desc:
                    _write_sidecar(file_path, final_desc)

                # Mark downloaded in DB right away too
                if file_path and record:
                    if final_desc and not record.description:
                        db.update_description(record.url, final_desc)
                    db.mark_downloaded(record.url, file_path)

    ydl_opts["progress_hooks"] = [_on_progress]
    tmp_cookie_file = ydl_opts.get("cookiefile")

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([r.url for r in records])
    finally:
        if tmp_cookie_file and Path(tmp_cookie_file).exists():
            Path(tmp_cookie_file).unlink(missing_ok=True)

    for record in records:
        # Skip records already handled by the progress hook
        if record.video_id in meta:
            continue

        # nooverwrites case — file existed, hook never fired
        file_path = str(_find_file(output_dir, record.video_id) or "")
        desc      = record.description

        if file_path:
            db.mark_downloaded(record.url, file_path)
            if desc:
                _write_sidecar(file_path, desc)
        else:
            db.mark_error(record.url, "File not found after download")

    print("\nDownload finished.")


def fetch_descriptions(
    records: "list[VideoRecord]",
    cookies_path: str | None = None,
    workers: int = 5,
) -> None:
    """
    Fetch video metadata (description/title) from TikTok via yt-dlp
    without downloading the actual video files.
    Uses a thread pool to fetch multiple videos in parallel.

    Args:
        records     : VideoRecord list — only records with empty description are processed.
        cookies_path: Path to cookies.json exported from the browser.
        workers     : Number of parallel threads (default 5).
    """
    from concurrent.futures import ThreadPoolExecutor, as_completed
    from db import get_db

    targets = [r for r in records if not r.description.strip()]
    if not targets:
        print("· All records already have descriptions — skipping metadata fetch.")
        return

    db    = get_db()
    total = len(targets)
    print(f"· Fetching descriptions for {total} video(s) ({workers} parallel)...")

    # Convert JSON cookies to Netscape once, share across threads
    tmp_cookie_file: str | None = None
    if cookies_path and Path(cookies_path).exists():
        tmp_cookie_file = _netscape_cookies(cookies_path)

    def _fetch_one(record: "VideoRecord") -> tuple[str, str]:
        ydl_opts: dict = {
            "quiet"       : True,
            "no_warnings" : True,
            "ignoreerrors": False,
            "extract_flat": False,
        }
        if tmp_cookie_file:
            ydl_opts["cookiefile"] = tmp_cookie_file
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(record.url, download=False)
        if not info:
            return record.video_id, ""
        return record.video_id, (info.get("description") or info.get("title") or "").strip()

    done = 0
    try:
        with ThreadPoolExecutor(max_workers=workers) as pool:
            futures = {pool.submit(_fetch_one, r): r for r in targets}
            for future in as_completed(futures):
                done += 1
                record = futures[future]
                try:
                    video_id, desc = future.result()
                    if desc and not _is_generic_title(desc):
                        db.update_description(record.url, desc)
                        record.description = desc
                        print(f"  [{done}/{total}] ✔ {video_id} — {desc[:60]}")
                    else:
                        print(f"  [{done}/{total}] ! {video_id} — no description found")
                except Exception as e:
                    print(f"  [{done}/{total}] ✖ {record.video_id} — {e}")
        # Pool has fully completed — safe to delete the temp cookie file now
    finally:
        if tmp_cookie_file and Path(tmp_cookie_file).exists():
            Path(tmp_cookie_file).unlink(missing_ok=True)

    print("· Description fetch complete.")


def _is_generic_title(desc: str) -> bool:
    """Returns True if desc is yt-dlp's fallback when no real description exists."""
    return desc.lower().startswith("tiktok video #")


def download_videos(urls: list[str], output_dir: str, cookies_path: str | None = None) -> None:
    """
    Legacy helper: download a plain list of URLs without DB tracking.
    """
    if not urls:
        print("No URLs provided.")
        return

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    print(f"Output directory  : {os.path.abspath(output_dir)}")
    print(f"Videos to download: {len(urls)}\n")

    ydl_opts = build_ydl_options(output_dir, cookies_path=cookies_path)

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        results = ydl.download(urls)

    print(f"\nDownload finished. yt-dlp exit code: {results}")


def _write_sidecar(video_path: str, description: str) -> None:
    """Write a .txt sidecar file next to the video with its description.
    Skips if description is empty or is yt-dlp's generic fallback title."""
    if not description:
        return
    # yt-dlp generates "TikTok video #<id>" when no description is available — skip it
    if description.lower().startswith("tiktok video #"):
        return
    sidecar = Path(video_path).with_suffix(".txt")
    try:
        sidecar.write_text(description, encoding="utf-8")
    except Exception as e:
        print(f"  ! Could not write sidecar {sidecar.name}: {e}")


def _find_file(output_dir: str, video_id: str) -> Path | None:
    """Look for a file containing the video_id in its name."""
    for f in Path(output_dir).glob(f"*{video_id}*"):
        if f.suffix in (".mp4", ".mkv", ".webm"):
            return f
    return None


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    URLS = [
        "https://www.tiktok.com/@dakpsico1/video/7570365422873169159",
        "https://www.tiktok.com/@dakpsico1/video/7660343642267127060",
    ]
    download_videos(URLS, "downloads")
